site_name: Computer Based Problem Solving
theme:
  name: material
  logo: assets/CS.svg
  favicon: assets/CS.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  font:
    text: Mali
    code: Noto Sans Mono
  features:
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.share
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  plugins:
    - search
    - offline
extra:
  social:
    - icon: material/numeric-2-box-multiple-outline
      link: https://icd2o.mths.ca
      name: ICD2O Course Website
    - icon: material/numeric-3-box-multiple-outline
      link: https://ics3u.mths.ca
      name: ICS3U Course Website
    - icon: material/numeric-4-box-multiple-outline
      link: https://ics4u.mths.ca
      name: ICS4U Course Website
  generator: false
copyright: Copyright &copy; 2020 - Mr Coxall
repo_url: https://github.com/mr-coxall
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
